from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SelectField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class CharacterForm(FlaskForm):
    character_name = StringField('Character Name', validators=[DataRequired()])
    discord_username = StringField('Discord Username', validators=[DataRequired()])
    character_class = SelectField('Character Class', choices=[('warrior', 'Warrior'), ('mage', 'Mage'), ('rogue', 'Rogue')], validators=[DataRequired()])
    alignment = SelectField('Alignment', choices=[('good', 'Good'), ('neutral', 'Neutral'), ('evil', 'Evil')], validators=[DataRequired()])
    race = SelectField('Race', choices=[('human', 'Human'), ('elf', 'Elf'), ('dwarf', 'Dwarf')], validators=[DataRequired()])
    age = IntegerField('Age', validators=[DataRequired()])
    height = StringField('Height', validators=[DataRequired()])
    weight = StringField('Weight', validators=[DataRequired()])
    gender = SelectField('Gender', choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], validators=[DataRequired()])
    eye_color = StringField('Eye Color', validators=[DataRequired()])
    hair_color = StringField('Hair Color', validators=[DataRequired()])
    skin_color = StringField('Skin Color', validators=[DataRequired()])
    favorite_weapon = StringField('Favorite Weapon', validators=[DataRequired()])
    character_description = TextAreaField('Character Description', validators=[DataRequired()])
    history = TextAreaField('History', validators=[DataRequired()])
    strength = IntegerField('Strength', validators=[DataRequired()])
    dexterity = IntegerField('Dexterity', validators=[DataRequired()])
    constitution = IntegerField('Constitution', validators=[DataRequired()])
    intelligence = IntegerField('Intelligence', validators=[DataRequired()])
    wisdom = IntegerField('Wisdom', validators=[DataRequired()])
    charisma = IntegerField('Charisma', validators=[DataRequired()])
    maximum_health = IntegerField('Maximum Health', validators=[DataRequired()])
    current_health = IntegerField('Current Health', validators=[DataRequired()])
    armor_class = IntegerField('Armor Class', validators=[DataRequired()])
    xp_points = IntegerField('XP Points', validators=[DataRequired()])
    platinum_coins = IntegerField('Platinum Coins', validators=[DataRequired()])
    gold_coins = IntegerField('Gold Coins', validators=[DataRequired()])
    silver_coins = IntegerField('Silver Coins', validators=[DataRequired()])
    copper_coins = IntegerField('Copper Coins', validators=[DataRequired()])
    feats = TextAreaField('Feats', validators=[DataRequired()])
    special_abilities = TextAreaField('Special Abilities', validators=[DataRequired()])
    skills = TextAreaField('Skills', validators=[DataRequired()])
    submit = SubmitField('Create Character')
