from extensions import db
from datetime import datetime

class Character(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    character_name = db.Column(db.String(100), nullable=False)
    discord_username = db.Column(db.String(100), nullable=False)
    character_class = db.Column(db.String(50), nullable=False)
    alignment = db.Column(db.String(50), nullable=False)
    race = db.Column(db.String(50), nullable=False)
    age = db.Column(db.Integer, nullable=False)
    height = db.Column(db.String(20), nullable=False)
    weight = db.Column(db.Integer, nullable=False)
    gender = db.Column(db.String(50), nullable=False)
    eye_color = db.Column(db.String(50), nullable=False)
    hair_color = db.Column(db.String(50), nullable=False)
    skin_color = db.Column(db.String(50), nullable=False)
    favorite_weapon = db.Column(db.String(100), nullable=False)
    character_description = db.Column(db.Text, nullable=False)
    history = db.Column(db.Text, nullable=False)
    strength = db.Column(db.Integer, nullable=False)
    dexterity = db.Column(db.Integer, nullable=False)
    constitution = db.Column(db.Integer, nullable=False)
    intelligence = db.Column(db.Integer, nullable=False)
    wisdom = db.Column(db.Integer, nullable=False)
    charisma = db.Column(db.Integer, nullable=False)
    maximum_health = db.Column(db.Integer, nullable=False)
    current_health = db.Column(db.Integer, nullable=False)
    xp_points = db.Column(db.Integer, nullable=False)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    date_modified = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    version_number = db.Column(db.Integer, default=1)
